// BUNDLE CONFIGURATION DATA
export const GET_EAS_CONFIGURATION_DATA_PENDING = 'GET_EAS_CONFIGURATION_DATA_PENDING';
export const GET_EAS_CONFIGURATION_DATA_FULFILLED = 'GET_EAS_CONFIGURATION_DATA_FULFILLED';
export const GET_EAS_CONFIGURATION_DATA_REJECTED = 'GET_EAS_CONFIGURATION_DATA_REJECTED';
//VSN SEARCH BY BRN
export const VSN_SEARCH_BY_BRN_PENDING='VSN_SEARCH_BY_BRN_PENDING';
export const VSN_SEARCH_BY_BRN_FULFILLED='VSN_SEARCH_BY_BRN_FULFILLED';
export const VSN_SEARCH_BY_BRN_REJECTED='VSN_SEARCH_BY_BRN_REJECTED';
//VSN search by msisnd or vsn
export const VSN_SEARCH_BY_MSISDN_VSN_PENDING='VSN_SEARCH_BY_MSISDN_VSN_PENDING';
export const VSN_SEARCH_BY_MSISDN_VSN_FULFILLED='VSN_SEARCH_BY_MSISDN_VSN_FULFILLED';
export const VSN_SEARCH_BY_MSISDN_VSN_REJECTED='VSN_SEARCH_BY_MSISDN_VSN_REJECTED';
//BRN validation in bcc
export const BRN_BCC_VALIDATION_PENDING='BRN_BCC_VALIDATION_PENDING';
export const BRN_BCC_VALIDATION_FULFILLED='BRN_BCC_VALIDATION_FULFILLED';
export const BRN_BCC_VALIDATION_REJECTED='BRN_BCC_VALIDATION_REJECTED';
//company info on basis of brn
export const COMPANY_INFO_BY_BRN_PENDING='COMPANY_INFO_BY_BRN_PENDING';
export const COMPANY_INFO_BY_BRN_FULFILLED='COMPANY_INFO_BY_BRN_FULFILLED';
export const COMPANY_INFO_BY_BRN_REJECTED='COMPANY_INFO_BY_BRN_REJECTED';
//fetchin registration details on basis of eas master reg id
export const FETCH_REG_DETAILS_BY_MASTER_REG_ID_PENDING='FETCH_REG_DETAILS_BY_MASTER_REG_ID_PENDING';
export const FETCH_REG_DETAILS_BY_MASTER_REG_ID_FULFILLED='FETCH_REG_DETAILS_BY_MASTER_REG_ID_FULFILLED';
export const FETCH_REG_DETAILS_BY_MASTER_REG_ID_REJECTED='FETCH_REG_DETAILS_BY_MASTER_REG_ID_REJECTED';
//fetch vsn contract info
export const FETCH_VSN_CONTRACT_INFO_PENDING='FETCH_VSN_CONTRACT_INFO_PENDING';
export const FETCH_VSN_CONTRACT_INFO_FULFILLED='FETCH_VSN_CONTRACT_INFO_FULFILLED';
export const FETCH_VSN_CONTRACT_INFO_REJECTED='FETCH_VSN_CONTRACT_INFO_REJECTED';
//fetch reg types
export const FETCH_REG_TYPES_PENDING='FETCH_REG_TYPES_PENDING';
export const FETCH_REG_TYPES_FULFILLED='FETCH_REG_TYPES_FULFILLED';
export const FETCH_REG_TYPES_REJECTED='FETCH_REG_TYPES_REJECTED';
//fetch rateplans
export const FETCH_RATEPLANS_PENDING='FETCH_RATEPLANS_PENDING';
export const FETCH_RATEPLANS_FULFILLED='FETCH_RATEPLANS_FULFILLED';
export const FETCH_RATEPLANS_REJECTED='FETCH_RATEPLANS_REJECTED';
//fetch sim types
export const FETCH_SIM_TYPES_PENDING='FETCH_SIM_TYPES_PENDING';
export const FETCH_SIM_TYPES_FULFILLED='FETCH_SIM_TYPES_FULFILLED';
export const FETCH_SIM_TYPES_REJECTED='FETCH_SIM_TYPES_REJECTED';
//fetch zeroltuin devices
export const FETCH_ZEROLUTION_DEVICES_PENDING='FETCH_ZEROLUTION_DEVICES_PENDING';
export const FETCH_ZEROLUTION_DEVICES_FULFILLED='FETCH_ZEROLUTION_DEVICES_FULFILLED';
export const FETCH_ZEROLUTION_DEVICES_REJECTED='FETCH_ZEROLUTION_DEVICES_REJECTED';
//fetch donor types
export const FETCH_DONOR_TYPES_PENDING='FETCH_DONOR_TYPES_PENDING';
export const FETCH_DONOR_TYPES_FULFILLED='FETCH_DONOR_TYPES_FULFILLED';
export const FETCH_DONOR_TYPES_REJECTED='FETCH_DONOR_TYPES_REJECTED';
//fetch zeroltuion devices
export const FETCH_ZEROLUTION_DEVICE_INFO_PENDING='FETCH_ZEROLUTION_DEVICE_INFO_PENDING';
export const FETCH_ZEROLUTION_DEVICE_INFO_FULFILLED='FETCH_ZEROLUTION_DEVICE_INFO_FULFILLED';
export const FETCH_ZEROLUTION_DEVICE_INFO_REJECTED='FETCH_ZEROLUTION_DEVICE_INFO_REJECTED';
//fetch device funds
export const FETCH_DEVICE_FUNDS_PENDING='FETCH_DEVICE_FUNDS_PENDING';
export const FETCH_DEVICE_FUNDS_FULFILLED='FETCH_DEVICE_FUNDS_FULFILLED';
export const FETCH_DEVICE_FUNDS_REJECTED='FETCH_DEVICE_FUNDS_REJECTED';
//fetch flexi fund devices
export const FETCH_FLEXI_FUND_DEVICES_PENDING='FETCH_FLEXI_FUND_DEVICES_PENDING';
export const FETCH_FLEXI_FUND_DEVICES_FULFILLED='FETCH_FLEXI_FUND_DEVICES_FULFILLED';
export const FETCH_FLEXI_FUND_DEVICES_REJECTED='FETCH_FLEXI_FUND_DEVICES_REJECTED';
//Send Uploaded File
export const SEND_FILE_PENDING = 'SEND_FILE_PENDING';
export const SEND_FILE_FULFILLED = 'SEND_FILE_FULFILLED';
export const SEND_FILE_REJECTED = 'SEND_FILE_REJECTED';
export const GET_UPLOADED_FILE_PENDING = 'GET_UPLOADED_FILE_PENDING';
export const GET_UPLOADED_FILE_FULFILLED = 'GET_UPLOADED_FILE_FULFILLED';
export const GET_UPLOADED_FILE_REJECTED = 'GET_UPLOADED_FILE_REJECTED';
export const SET_COMPANY_INFO_PENDING = 'SET_COMPANY_INFO_PENDING';
export const SET_COMPANY_INFO_FULFILLED = 'SET_COMPANY_INFO_FULFILLED';
//fetch post codes
export const FETCH_POST_CODE_HINT_PENDING='FETCH_POST_CODE_HINT_PENDING';
export const FETCH_POST_CODE_HINT_FULFILLED='FETCH_POST_CODE_HINT_FULFILLED';
export const FETCH_POST_CODE_HINT_REJECTED='FETCH_POST_CODE_HINT_REJECTED';
//fetch dealer name and dealer code
export const SUBMISSION_INFO_PENDING='SUBMISSION_INFO_PENDING';
export const SUBMISSION_INFO_FULFILLED='SUBMISSION_INFO_FULFILLED';
export const SUBMISSION_INFO_REJECTED='SUBMISSION_INFO_REJECTED';
//fetch account manager details
export const ACCOUNT_MANAGER_INFO_PENDING='ACCOUNT_MANAGER_INFO_PENDING';
export const ACCOUNT_MANAGER_INFO_FULFILLED='ACCOUNT_MANAGER_INFO_FULFILLED';
export const ACCOUNT_MANAGER_INFO_REJECTED='ACCOUNT_MANAGER_INFO_REJECTED';
//fetch supporting center details
export const SUPPORTING_CENTER_INFO_PENDING='SUPPORTING_CENTER_INFO_PENDING';
export const SUPPORTING_CENTER_INFO_FULFILLED='SUPPORTING_CENTER_INFO_FULFILLED';
export const SUPPORTING_CENTER_INFO_REJECTED='SUPPORTING_CENTER_INFO_REJECTED';
//send submission uploaded file
export const SUBMISSION_SEND_FILE_PENDING='SUBMISSION_SEND_FILE_PENDING';
export const SUBMISSION_SEND_FILE_FULFILLED='SUBMISSION_SEND_FILE_FULFILLED';
export const SUBMISSION_SEND_FILE_REJECTED='SUBMISSION_SEND_FILE_REJECTED';
export const SUBMISSION_UPLOAD_FILE_PENDING='SUBMISSION_UPLOAD_FILE_PENDING';
export const SUBMISSION_UPLOAD_FILE_FULFILLED='SUBMISSION_UPLOAD_FILE_FULFILLED';
export const SUBMISSION_UPLOAD_FILE_REJECTED='SUBMISSION_UPLOAD_FILE_REJECTED';

export const FETCH_VAS_POPUP_DATA_PENDING='FETCH_VAS_POPUP_DATA_PENDING';
export const FETCH_VAS_POPUP_DATA_FULFILLED='FETCH_VAS_POPUP_DATA_FULFILLED';
export const FETCH_VAS_POPUP_DATA_REJECTED='FETCH_VAS_POPUP_DATA_REJECTED';

export const VALIDATE_LINE_PENDING='VALIDATE_LINE_PENDING';
export const VALIDATE_LINE_FULFILLED='VALIDATE_LINE_FULFILLED';
export const VALIDATE_LINE_REJECTED='VALIDATE_LINE_REJECTED';

export const FETCH_DEVICE_FUND_CONTRACTS_PENDING='FETCH_DEVICE_FUND_CONTRACTS_PENDING';
export const FETCH_DEVICE_FUND_CONTRACTS_FULFILLED='FETCH_DEVICE_FUND_CONTRACTS_FULFILLED';
export const FETCH_DEVICE_FUND_CONTRACTS_REJECTED='FETCH_DEVICE_FUND_CONTRACTS_REJECTED';

//fetch zeroltuion devices
export const FETCH_FUND_DEVICE_INFO_PENDING='FETCH_FUND_DEVICE_INFO_PENDING';
export const FETCH_FUND_DEVICE_INFO_FULFILLED='FETCH_FUND_DEVICE_INFO_FULFILLED';
export const FETCH_FUND_DEVICE_INFO_REJECTED='FETCH_FUND_DEVICE_INFO_REJECTED';

export const GET_DEVICE_FUND_CONTRACTS_PENDING='GET_DEVICE_FUND_CONTRACTS_PENDING';
export const GET_DEVICE_FUND_CONTRACTS_FULFILLED='GET_DEVICE_FUND_CONTRACTS_FULFILLED';
export const GET_DEVICE_FUND_CONTRACTS_REJECTED='GET_DEVICE_FUND_CONTRACTS_REJECTED';

export const GET_ADDED_FUND_DEVICES_PENDING='GET_ADDED_FUND_DEVICES_PENDING';
export const GET_ADDED_FUND_DEVICES_FULFILLED='GET_ADDED_FUND_DEVICES_FULFILLED';
export const GET_ADDED_FUND_DEVICES_REJECTED='GET_ADDED_FUND_DEVICES_REJECTED';


export const SET_DEVICE_FUNDS_PENDING='SET_DEVICE_FUNDS_PENDING';
export const SET_DEVICE_FUNDS_FULFILLED='SET_DEVICE_FUNDS_FULFILLED';
export const SET_DEVICE_FUNDS_REJECTED='SET_DEVICE_FUNDS_REJECTED';


//fetch approval submission
export const APPROVAL_SUBMISSION_INFO_PENDING='APPROVAL_SUBMISSION_INFO_PENDING';
export const APPROVAL_SUBMISSION_INFO_FULFILLED='APPROVAL_SUBMISSION_INFO_FULFILLED';
export const APPROVAL_SUBMISSION_INFO_REJECTED='APPROVAL_SUBMISSION_INFO_REJECTED';
//validate parentId HierId
export const VALIDATE_PARENTID_HIERID_PENDING='VALIDATE_PARENTID_HIERID_PENDING';
export const VALIDATE_PARENTID_HIERID_FULFILLED='VALIDATE_PARENTID_HIERID_FULFILLED';
export const VALIDATE_PARENTID_HIERID_REJECTED='VALIDATE_PARENTID_HIERID_REJECTED';
//GET PAYMENT DETAILS

export const GET_PAYMENT_DETAILS_PENDING='GET_PAYMENT_DETAILS_PENDING';
export const GET_PAYMENT_DETAILS_FULFILLED='GET_PAYMENT_DETAILS_FULFILLED';
export const GET_PAYMENT_DETAILS_REJECTED='GET_PAYMENT_DETAILS_REJECTED';

export const GET_VIEW_SUBMISSION_INFO_PENDING='GET_VIEW_SUBMISSION_INFO_PENDING';
export const GET_VIEW_SUBMISSION_INFO_FULFILLED='GET_VIEW_SUBMISSION_INFO_FULFILLED';
export const GET_VIEW_SUBMISSION_INFO_REJECTED='GET_VIEW_SUBMISSION_INFO_REJECTED';

export const FETCH_ASSIGN_TO_LIST_PENDING='FETCH_ASSIGN_TO_LIST_PENDING';
export const FETCH_ASSIGN_TO_LIST_FULFILLED='FETCH_ASSIGN_TO_LIST_FULFILLED';
export const FETCH_ASSIGN_TO_LIST_REJECTED='FETCH_ASSIGN_TO_LIST_REJECTED';


export const RESET_PARENTID_HIERID_STATUS_PENDING='RESET_PARENTID_HIERID_STATUS_PENDING';
export const RESET_PARENTID_HIERID_STATUS_FULFILLED='RESET_PARENTID_HIERID_STATUS_FULFILLED';
export const RESET_PARENTID_HIERID_STATUS_REJECTED='RESET_PARENTID_HIERID_STATUS_REJECTED';

export const VAS_RULE_CHECK_PENDING='VAS_RULE_CHECK_PENDING';
export const VAS_RULE_CHECK_FULFILLED='VAS_RULE_CHECK_FULFILLED';
export const VAS_RULE_CHECK_REJECTED='VAS_RULE_CHECK_REJECTED';

export const CONTRACT_CHECK_PENDING='CONTRACT_CHECK_PENDING';
export const CONTRACT_CHECK_FULFILLED='CONTRACT_CHECK_FULFILLED';
export const CONTRACT_CHECK_REJECTED='CONTRACT_CHECK_REJECTED';

export const SET_APPROVAL_DEVICE_FUNDS_PENDING='SET_APPROVAL_DEVICE_FUNDS_PENDING';
export const SET_APPROVAL_DEVICE_FUNDS_FULFILLED='SET_APPROVAL_DEVICE_FUNDS_FULFILLED';
export const SET_APPROVAL_DEVICE_FUNDS_REJECTED='SET_APPROVAL_DEVICE_FUNDS_REJECTED';

export const GET_VSN_DETAILS_PENDING='GET_VSN_DETAILS_PENDING';
export const GET_VSN_DETAILS_FULFILLED='GET_VSN_DETAILS_FULFILLED';
export const GET_VSN_DETAILS_REJECTED='GET_VSN_DETAILS_REJECTED';

export const GET_PROMOTIONS_PENDING='GET_PROMOTIONS_PENDING';
export const GET_PROMOTIONS_FULFILLED='GET_PROMOTIONS_FULFILLED';
export const GET_PROMOTIONS_REJECTED='GET_PROMOTIONS_REJECTED';


export const GET_DEVICE_LIST_ERF_PENDING='GET_DEVICE_LIST_ERF_PENDING';
export const GET_DEVICE_LIST_ERF_FULFILLED='GET_DEVICE_LIST_ERF_FULFILLED';
export const GET_DEVICE_LIST_ERF_REJECTED='GET_DEVICE_LIST_ERF_REJECTED';
export const SET_OLD_DEVICE_FUNDS_PENDING='SET_OLD_DEVICE_FUNDS_PENDING';
export const SET_OLD_DEVICE_FUNDS_FULFILLED='SET_OLD_DEVICE_FUNDS_FULFILLED';
export const SET_OLD_DEVICE_FUNDS_REJECTED='SET_OLD_DEVICE_FUNDS_REJECTED';
export const SEARCH_PAYMENT_PENDING='SEARCH_PAYMENT_PENDING';
export const SEARCH_PAYMENT_FULFILLED='SEARCH_PAYMENT_FULFILLED';
export const SEARCH_PAYMENT_REJECTED='SEARCH_PAYMENT_REJECTED';

export const GET_PROD_GRP_CHANGE_PENDING='GET_PROD_GRP_CHANGE_PENDING';
export const GET_PROD_GRP_CHANGE_FULFILLED='GET_PROD_GRP_CHANGE_FULFILLED';
export const GET_PROD_GRP_CHANGE_REJECTED='GET_PROD_GRP_CHANGE_REJECTED';

export const SEARCH_CHANGE_PENDING='SEARCH_CHANGE_PENDING';
export const SEARCH_CHANGE_FULFILLED='SEARCH_CHANGE_FULFILLED';
export const SEARCH_CHANGE_REJECTED='SEARCH_CHANGE_REJECTED';

export const SEND_FILE_URL_DEALER_SEARCH_PENDING='SEND_FILE_URL_DEALER_SEARCH_PENDING';
export const SEND_FILE_URL_DEALER_SEARCH_FULFILLED='SEND_FILE_URL_DEALER_SEARCH_FULFILLED';
export const SEND_FILE_URL_DEALER_SEARCH_REJECTED='SEND_FILE_URL_DEALER_SEARCH_REJECTED';
export const GET_AUTOMATED_REPORT_NAME_PENDING = 'GET_AUTOMATED_REPORT_NAME_PENDING';
export const GET_AUTOMATED_REPORT_NAME_FULFILLED = 'GET_AUTOMATED_REPORT_NAME_FULFILLED';
export const GET_AUTOMATED_REPORT_NAME_REJECTED = 'GET_AUTOMATED_REPORT_NAME_REJECTED';
			
export const GENERATE_REPORT_DATA_PENDING = 'GENERATE_REPORT_DATA_PENDING';
export const GENERATE_REPORT_DATA_FULFILLED = 'GENERATE_REPORT_DATA_FULFILLED';
export const GENERATE_REPORT_DATA_REJECTED = 'GENERATE_REPORT_DATA_REJECTED';


export const GET_REPORTS_EXECUTION_HISTORY_PENDING='GET_REPORTS_EXECUTION_HISTORY_PENDING';
export const GET_REPORTS_EXECUTION_HISTORY_FULFILLED='GET_REPORTS_EXECUTION_HISTORY_FULFILLED';
export const GET_REPORTS_EXECUTION_HISTORY_REJECTED='GET_REPORTS_EXECUTION_HISTORY_REJECTED';

export const GET_CUSTOM_REPORT_INPUTS_PENDING='GET_CUSTOM_REPORT_INPUTS_PENDING';
export const GET_CUSTOM_REPORT_INPUTS_FULFILLED='GET_CUSTOM_REPORT_INPUTS_FULFILLED';
export const GET_CUSTOM_REPORT_INPUTS_REJECTED='GET_CUSTOM_REPORT_INPUTS_REJECTED';

//fetch reg types for obs
export const FETCH_REG_TYPES_OBS_PENDING='FETCH_REG_TYPES_OBS_PENDING';
export const FETCH_REG_TYPES_OBS_FULFILLED='FETCH_REG_TYPES_OBS_FULFILLED';
export const FETCH_REG_TYPES_OBS_REJECTED='FETCH_REG_TYPES_OBS_REJECTED';

//fetch rateplans for obs
export const FETCH_RATEPLANS_OBS_PENDING='FETCH_RATEPLANS_OBS_PENDING';
export const FETCH_RATEPLANS_OBS_FULFILLED='FETCH_RATEPLANS_OBS_FULFILLED';
export const FETCH_RATEPLANS_OBS_REJECTED='FETCH_RATEPLANS_OBS_REJECTED';

export const VSN_OBS_SEARCH_BY_BRN_PENDING='VSN_OBS_SEARCH_BY_BRN_PENDING';
export const VSN_OBS_SEARCH_BY_BRN_FULFILLED='VSN_OBS_SEARCH_BY_BRN_FULFILLED';
export const VSN_OBS_SEARCH_BY_BRN_REJECTED='VSN_OBS_SEARCH_BY_BRN_REJECTED';

export const GET_BCC_VALIDATION_PENDING='GET_BCC_VALIDATION_PENDING';
export const GET_BCC_VALIDATION_FULFILLED='GET_BCC_VALIDATION_FULFILLED';
export const GET_BCC_VALIDATION_REJECTED='GET_BCC_VALIDATION_REJECTED';

export const GET_RATEPLAN_DEVICE_MAP_LIST_PENDING='GET_RATEPLAN_DEVICE_MAP_LIST_PENDING';
export const GET_RATEPLAN_DEVICE_MAP_LIST_FULFILLED='GET_RATEPLAN_DEVICE_MAP_LIST_FULFILLED';
export const GET_RATEPLAN_DEVICE_MAP_LIST_REJECTED='GET_RATEPLAN_DEVICE_MAP_LIST_REJECTED';

export const VALIDATE_LINE_EXISTING_GROUP_PENDING='VALIDATE_LINE_EXISTING_GROUP_PENDING';
export const VALIDATE_LINE_EXISTING_GROUP_FULFILLED='VALIDATE_LINE_EXISTING_GROUP_FULFILLED';
export const VALIDATE_LINE_EXISTING_GROUP_REJECTED='VALIDATE_LINE_EXISTING_GROUP_REJECTED';




export const GET_BULK_USERS_PENDING='GET_BULK_USERS_PENDING';
export const GET_BULK_USERS_FULFILLED='GET_BULK_USERS_FULFILLED';
export const GET_BULK_USERS_REJECTED='GET_BULK_USERS_REJECTED';


export const GET_BULK_ORDERS_DATA_PENDING='GET_BULK_ORDERS_DATA_PENDING';
export const GET_BULK_ORDERS_DATA_FULFILLED='GET_BULK_ORDERS_DATA_FULFILLED';
export const GET_BULK_ORDERS_DATA_REJECTED='GET_BULK_ORDERS_DATA_REJECTED';

export const GET_TEMPLATE_PENDING='GET_TEMPLATE_PENDING';
export const GET_TEMPLATE_FULFILLED='GET_TEMPLATE_FULFILLED';
export const GET_TEMPLATE_REJECTED='GET_TEMPLATE_REJECTED';


export const GET_SIM_TYPE_REPLCMT_REASON_PENDING='GET_SIM_TYPE_REPLCMT_REASON_PENDING';
export const GET_SIM_TYPE_REPLCMT_REASON_FULFILLED='GET_SIM_TYPE_REPLCMT_REASON_FULFILLED';
export const GET_SIM_TYPE_REPLCMT_REASON_REJECTED='GET_SIM_TYPE_REPLCMT_REASON_REJECTED';

export const GET_TEMPLATE_BULKSIM_PENDING = 'GET_TEMPLATE_BULKSIM_PENDING';
export const GET_TEMPLATE_BULKSIM_FULFILLED = 'GET_TEMPLATE_BULKSIM_FULFILLED';
export const GET_TEMPLATE_BULKSIM_REJECTED = 'GET_TEMPLATE_BULKSIM_REJECTED';

export const GET_OBS_DEVICES_PENDING='GET_OBS_DEVICES_PENDING';
export const GET_OBS_DEVICES_FULFILLED='GET_OBS_DEVICES_FULFILLED';
export const GET_OBS_DEVICES_REJECTED='GET_OBS_DEVICES_REJECTED';

export const FETCH_OBS_DEVICE_INFO_PENDING='FETCH_OBS_DEVICE_INFO_PENDING';
export const FETCH_OBS_DEVICE_INFO_FULFILLED='FETCH_OBS_DEVICE_INFO_FULFILLED';
export const FETCH_OBS_DEVICE_INFO_REJECTED='FETCH_OBS_DEVICE_INFO_REJECTED';

export const FETCH_ZEROLUTION_DEVICE_REPORT_PENDING='FETCH_ZEROLUTION_DEVICE_REPORT_PENDING';
export const FETCH_ZEROLUTION_DEVICE_REPORT_FULFILLED='FETCH_ZEROLUTION_DEVICE_REPORT_FULFILLED';
export const FETCH_ZEROLUTION_DEVICE_REPORT_REJECTED='FETCH_ZEROLUTION_DEVICE_REPORT_REJECTED';

export const DOWNLOAD_ZEROLUTION_DEVICE_REPORT_PENDING='DOWNLOAD_ZEROLUTION_DEVICE_REPORT_PENDING';
export const DOWNLOAD_ZEROLUTION_DEVICE_REPORT_FULFILLED='DOWNLOAD_ZEROLUTION_DEVICE_REPORT_FULFILLED';
export const DOWNLOAD_ZEROLUTION_DEVICE_REPORT_REJECTED='DOWNLOAD_ZEROLUTION_DEVICE_REPORT_REJECTED';


export const EXISTING_SHAREABLE_LINES_COUNT_PENDING='EXISTING_SHAREABLE_LINES_COUNT_PENDING';
export const EXISTING_SHAREABLE_LINES_COUNT_FULFILLED='EXISTING_SHAREABLE_LINES_COUNT_FULFILLED';
export const EXISTING_SHAREABLE_LINES_COUNT_REJECTED='EXISTING_SHAREABLE_LINES_COUNT_REJECTED';



export const EXISTING_SHAREABLE_LINES_COUNT_EXCLUDE_CRP_PENDING='EXISTING_SHAREABLE_LINES_COUNT_EXCLUDE_CRP_PENDING';
export const EXISTING_SHAREABLE_LINES_COUNT_EXCLUDE_CRP_FULFILLED='EXISTING_SHAREABLE_LINES_COUNT_EXCLUDE_CRP_FULFILLED';
export const EXISTING_SHAREABLE_LINES_COUNT_EXCLUDE_CRP_REJECTED='EXISTING_SHAREABLE_LINES_COUNT_EXCLUDE_CRP_REJECTED';




